version: 2

rn_defaults: &rn_defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10.9

jobs:
  install-dependencies:
    <<: *rn_defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project 
      - restore_cache:
          keys:
          - v1-0-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-0-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-0-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
            - yarn.lock

      # install rustup
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: echo 'export PATH=$HOME/.cargo/bin/:$PATH' >> $BASH_ENV
      # use nightly version. 
      # // FIXME: This is hardcoded but taken from js-cardano-wasm repo
      # which is checked out later
      - run: rustup install nightly-2018-06-05
      - run: rustup target add wasm32-unknown-unknown --toolchain nightly-2018-06-05

      # Because npm link will write in this path
      - run: sudo chown -R "$(whoami):$(whoami)" /usr/local/lib/node_modules
      - run: ./build_cardano_rust.sh

      - persist_to_workspace:
          root: .
          paths: .

  flow:
    <<: *rn_defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn flow

  test:
    <<: *rn_defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test

  lint:
    <<: *rn_defaults
    steps:
      - attach_workspace:
         at: ~/project

      # Because npm link will write in this path
      - run: sudo chown -R "$(whoami):$(whoami)" /usr/local/lib/node_modules
      - run: npm link rust-cardano-crypto
      - run: yarn lint

  android:
    working_directory: ~/project/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Android build
          command: ./gradlew assembleRelease

workflows:
  version: 2
  main:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - flow:
          requires:
            - install-dependencies
      - test:
          requires:
            - install-dependencies
#      - android:
#          requires: 
#            - install-dependencies
#            - lint
#            - flow
